// Code generated by MockGen. DO NOT EDIT.
// Source: fyne.io/fyne/v2/data/binding (interfaces: UntypedTree)
//
// Generated by this command:
//
//	mockgen -package mocks_binding -destination mocks/binding/tree.go fyne.io/fyne/v2/data/binding UntypedTree
//

// Package mocks_binding is a generated GoMock package.
package mocks_binding

import (
	reflect "reflect"

	binding "fyne.io/fyne/v2/data/binding"
	gomock "go.uber.org/mock/gomock"
)

// MockUntypedTree is a mock of UntypedTree interface.
type MockUntypedTree[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockUntypedTreeMockRecorder[T]
	isgomock struct{}
}

// MockUntypedTreeMockRecorder is the mock recorder for MockUntypedTree.
type MockUntypedTreeMockRecorder[T any] struct {
	mock *MockUntypedTree[T]
}

// NewMockUntypedTree creates a new mock instance.
func NewMockUntypedTree[T any](ctrl *gomock.Controller) *MockUntypedTree[T] {
	mock := &MockUntypedTree[T]{ctrl: ctrl}
	mock.recorder = &MockUntypedTreeMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUntypedTree[T]) EXPECT() *MockUntypedTreeMockRecorder[T] {
	return m.recorder
}

// AddListener mocks base method.
func (m *MockUntypedTree[T]) AddListener(arg0 binding.DataListener) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddListener", arg0)
}

// AddListener indicates an expected call of AddListener.
func (mr *MockUntypedTreeMockRecorder[T]) AddListener(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddListener", reflect.TypeOf((*MockUntypedTree[T])(nil).AddListener), arg0)
}

// Append mocks base method.
func (m *MockUntypedTree[T]) Append(parent, id string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Append", parent, id, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Append indicates an expected call of Append.
func (mr *MockUntypedTreeMockRecorder[T]) Append(parent, id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockUntypedTree[T])(nil).Append), parent, id, value)
}

// ChildIDs mocks base method.
func (m *MockUntypedTree[T]) ChildIDs(arg0 string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChildIDs", arg0)
	ret0, _ := ret[0].([]string)
	return ret0
}

// ChildIDs indicates an expected call of ChildIDs.
func (mr *MockUntypedTreeMockRecorder[T]) ChildIDs(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChildIDs", reflect.TypeOf((*MockUntypedTree[T])(nil).ChildIDs), arg0)
}

// Get mocks base method.
func (m *MockUntypedTree[T]) Get() (map[string][]string, map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get")
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(map[string]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockUntypedTreeMockRecorder[T]) Get() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUntypedTree[T])(nil).Get))
}

// GetItem mocks base method.
func (m *MockUntypedTree[T]) GetItem(id string) (binding.DataItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", id)
	ret0, _ := ret[0].(binding.DataItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockUntypedTreeMockRecorder[T]) GetItem(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockUntypedTree[T])(nil).GetItem), id)
}

// GetValue mocks base method.
func (m *MockUntypedTree[T]) GetValue(id string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", id)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValue indicates an expected call of GetValue.
func (mr *MockUntypedTreeMockRecorder[T]) GetValue(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockUntypedTree[T])(nil).GetValue), id)
}

// Prepend mocks base method.
func (m *MockUntypedTree[T]) Prepend(parent, id string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepend", parent, id, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Prepend indicates an expected call of Prepend.
func (mr *MockUntypedTreeMockRecorder[T]) Prepend(parent, id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepend", reflect.TypeOf((*MockUntypedTree[T])(nil).Prepend), parent, id, value)
}

// Remove mocks base method.
func (m *MockUntypedTree[T]) Remove(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockUntypedTreeMockRecorder[T]) Remove(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockUntypedTree[T])(nil).Remove), id)
}

// RemoveListener mocks base method.
func (m *MockUntypedTree[T]) RemoveListener(arg0 binding.DataListener) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveListener", arg0)
}

// RemoveListener indicates an expected call of RemoveListener.
func (mr *MockUntypedTreeMockRecorder[T]) RemoveListener(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveListener", reflect.TypeOf((*MockUntypedTree[T])(nil).RemoveListener), arg0)
}

// Set mocks base method.
func (m *MockUntypedTree[T]) Set(ids map[string][]string, values map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ids, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockUntypedTreeMockRecorder[T]) Set(ids, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockUntypedTree[T])(nil).Set), ids, values)
}

// SetValue mocks base method.
func (m *MockUntypedTree[T]) SetValue(id string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetValue", id, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetValue indicates an expected call of SetValue.
func (mr *MockUntypedTreeMockRecorder[T]) SetValue(id, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetValue", reflect.TypeOf((*MockUntypedTree[T])(nil).SetValue), id, value)
}
