// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ui/viewmodel/editor_viewmodel_test.go
//
// Generated by this command:
//
//	mockgen -package mock_editor -destination mocks/editor/closable.go -source internal/ui/viewmodel/editor_viewmodel_test.go ClosableEditor
//

// Package mock_editor is a generated GoMock package.
package mock_editor
