// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ui/viewmodel/editor_viewmodel_test.go
//
// Generated by this command:
//
//	mockgen -package mock_editor -destination mocks/editor/closable.go -source internal/ui/viewmodel/editor_viewmodel_test.go ClosableEditor
//

// Package mock_editor is a generated GoMock package.
package mock_editor

import (
	io "io"
	reflect "reflect"

	fyne "fyne.io/fyne/v2"
	directory "github.com/thomas-marquis/s3-box/internal/domain/directory"
	gomock "go.uber.org/mock/gomock"
)

// MockClosableEditor is a mock of ClosableEditor interface.
type MockClosableEditor struct {
	ctrl     *gomock.Controller
	recorder *MockClosableEditorMockRecorder
	isgomock struct{}
}

// MockClosableEditorMockRecorder is the mock recorder for MockClosableEditor.
type MockClosableEditorMockRecorder struct {
	mock *MockClosableEditor
}

// NewMockClosableEditor creates a new mock instance.
func NewMockClosableEditor(ctrl *gomock.Controller) *MockClosableEditor {
	mock := &MockClosableEditor{ctrl: ctrl}
	mock.recorder = &MockClosableEditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClosableEditor) EXPECT() *MockClosableEditorMockRecorder {
	return m.recorder
}

// BeforeClose mocks base method.
func (m *MockClosableEditor) BeforeClose(cb func(bool)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BeforeClose", cb)
}

// BeforeClose indicates an expected call of BeforeClose.
func (mr *MockClosableEditorMockRecorder) BeforeClose(cb any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeClose", reflect.TypeOf((*MockClosableEditor)(nil).BeforeClose), cb)
}

// CreateWidget mocks base method.
func (m *MockClosableEditor) CreateWidget() fyne.CanvasObject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWidget")
	ret0, _ := ret[0].(fyne.CanvasObject)
	return ret0
}

// CreateWidget indicates an expected call of CreateWidget.
func (mr *MockClosableEditorMockRecorder) CreateWidget() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWidget", reflect.TypeOf((*MockClosableEditor)(nil).CreateWidget))
}

// File mocks base method.
func (m *MockClosableEditor) File() *directory.File {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "File")
	ret0, _ := ret[0].(*directory.File)
	return ret0
}

// File indicates an expected call of File.
func (mr *MockClosableEditorMockRecorder) File() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "File", reflect.TypeOf((*MockClosableEditor)(nil).File))
}

// OnLoaded mocks base method.
func (m *MockClosableEditor) OnLoaded(fileContent directory.FileContent, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnLoaded", fileContent, err)
}

// OnLoaded indicates an expected call of OnLoaded.
func (mr *MockClosableEditorMockRecorder) OnLoaded(fileContent, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnLoaded", reflect.TypeOf((*MockClosableEditor)(nil).OnLoaded), fileContent, err)
}

// OnSaved mocks base method.
func (m *MockClosableEditor) OnSaved(newContent string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnSaved", newContent, err)
}

// OnSaved indicates an expected call of OnSaved.
func (mr *MockClosableEditorMockRecorder) OnSaved(newContent, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSaved", reflect.TypeOf((*MockClosableEditor)(nil).OnSaved), newContent, err)
}

// SetCloser mocks base method.
func (m *MockClosableEditor) SetCloser(closer io.Closer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCloser", closer)
}

// SetCloser indicates an expected call of SetCloser.
func (mr *MockClosableEditorMockRecorder) SetCloser(closer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCloser", reflect.TypeOf((*MockClosableEditor)(nil).SetCloser), closer)
}

// Window mocks base method.
func (m *MockClosableEditor) Window() fyne.Window {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Window")
	ret0, _ := ret[0].(fyne.Window)
	return ret0
}

// Window indicates an expected call of Window.
func (mr *MockClosableEditorMockRecorder) Window() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Window", reflect.TypeOf((*MockClosableEditor)(nil).Window))
}
