// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/ui/views/editors/editor (interfaces: Editor)
//
// Generated by this command:
//
//	mockgen -package mock_editor -destination mocks/editor/editor.go github.com/thomas-marquis/s3-box/internal/ui/views/editors/editor Editor
//

// Package mock_editor is a generated GoMock package.
package mock_editor

import (
	reflect "reflect"

	fyne "fyne.io/fyne/v2"
	directory "github.com/thomas-marquis/s3-box/internal/domain/directory"
	gomock "go.uber.org/mock/gomock"
)

// MockEditor is a mock of Editor interface.
type MockEditor struct {
	ctrl     *gomock.Controller
	recorder *MockEditorMockRecorder
	isgomock struct{}
}

// MockEditorMockRecorder is the mock recorder for MockEditor.
type MockEditorMockRecorder struct {
	mock *MockEditor
}

// NewMockEditor creates a new mock instance.
func NewMockEditor(ctrl *gomock.Controller) *MockEditor {
	mock := &MockEditor{ctrl: ctrl}
	mock.recorder = &MockEditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditor) EXPECT() *MockEditorMockRecorder {
	return m.recorder
}

// CreateWidget mocks base method.
func (m *MockEditor) CreateWidget() fyne.CanvasObject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWidget")
	ret0, _ := ret[0].(fyne.CanvasObject)
	return ret0
}

// CreateWidget indicates an expected call of CreateWidget.
func (mr *MockEditorMockRecorder) CreateWidget() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWidget", reflect.TypeOf((*MockEditor)(nil).CreateWidget))
}

// File mocks base method.
func (m *MockEditor) File() *directory.File {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "File")
	ret0, _ := ret[0].(*directory.File)
	return ret0
}

// File indicates an expected call of File.
func (mr *MockEditorMockRecorder) File() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "File", reflect.TypeOf((*MockEditor)(nil).File))
}

// OnLoaded mocks base method.
func (m *MockEditor) OnLoaded(fileContent directory.FileContent, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnLoaded", fileContent, err)
}

// OnLoaded indicates an expected call of OnLoaded.
func (mr *MockEditorMockRecorder) OnLoaded(fileContent, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnLoaded", reflect.TypeOf((*MockEditor)(nil).OnLoaded), fileContent, err)
}

// OnSaved mocks base method.
func (m *MockEditor) OnSaved(newContent string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnSaved", newContent, err)
}

// OnSaved indicates an expected call of OnSaved.
func (mr *MockEditorMockRecorder) OnSaved(newContent, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSaved", reflect.TypeOf((*MockEditor)(nil).OnSaved), newContent, err)
}

// Window mocks base method.
func (m *MockEditor) Window() fyne.Window {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Window")
	ret0, _ := ret[0].(fyne.Window)
	return ret0
}

// Window indicates an expected call of Window.
func (mr *MockEditorMockRecorder) Window() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Window", reflect.TypeOf((*MockEditor)(nil).Window))
}
