// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/ui/views/editors/editor (interfaces: Factory)
//
// Generated by this command:
//
//	mockgen -package mock_editor -destination mocks/editor/factory.go github.com/thomas-marquis/s3-box/internal/ui/views/editors/editor Factory
//

// Package mock_editor is a generated GoMock package.
package mock_editor

import (
	reflect "reflect"

	fyne "fyne.io/fyne/v2"
	event "github.com/thomas-marquis/it-happened/event"
	directory "github.com/thomas-marquis/s3-box/internal/domain/directory"
	editor "github.com/thomas-marquis/s3-box/internal/ui/views/editors/editor"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// DefaultFileRegexpPattern mocks base method.
func (m *MockFactory) DefaultFileRegexpPattern() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DefaultFileRegexpPattern")
	ret0, _ := ret[0].(string)
	return ret0
}

// DefaultFileRegexpPattern indicates an expected call of DefaultFileRegexpPattern.
func (mr *MockFactoryMockRecorder) DefaultFileRegexpPattern() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DefaultFileRegexpPattern", reflect.TypeOf((*MockFactory)(nil).DefaultFileRegexpPattern))
}

// DisplayLabel mocks base method.
func (m *MockFactory) DisplayLabel() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisplayLabel")
	ret0, _ := ret[0].(string)
	return ret0
}

// DisplayLabel indicates an expected call of DisplayLabel.
func (mr *MockFactoryMockRecorder) DisplayLabel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisplayLabel", reflect.TypeOf((*MockFactory)(nil).DisplayLabel))
}

// Name mocks base method.
func (m *MockFactory) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockFactoryMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockFactory)(nil).Name))
}

// New mocks base method.
func (m *MockFactory) New(bus event.Bus, window fyne.Window, file *directory.File) editor.Editor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", bus, window, file)
	ret0, _ := ret[0].(editor.Editor)
	return ret0
}

// New indicates an expected call of New.
func (mr *MockFactoryMockRecorder) New(bus, window, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockFactory)(nil).New), bus, window, file)
}
