// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/ui/views/editors/editor (interfaces: MappingRepository)
//
// Generated by this command:
//
//	mockgen -package mock_editor -destination mocks/editor/mapping_repository.go github.com/thomas-marquis/s3-box/internal/ui/views/editors/editor MappingRepository
//

// Package mock_editor is a generated GoMock package.
package mock_editor

import (
	reflect "reflect"

	editor "github.com/thomas-marquis/s3-box/internal/ui/views/editors/editor"
	gomock "go.uber.org/mock/gomock"
)

// MockMappingRepository is a mock of MappingRepository interface.
type MockMappingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMappingRepositoryMockRecorder
	isgomock struct{}
}

// MockMappingRepositoryMockRecorder is the mock recorder for MockMappingRepository.
type MockMappingRepositoryMockRecorder struct {
	mock *MockMappingRepository
}

// NewMockMappingRepository creates a new mock instance.
func NewMockMappingRepository(ctrl *gomock.Controller) *MockMappingRepository {
	mock := &MockMappingRepository{ctrl: ctrl}
	mock.recorder = &MockMappingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMappingRepository) EXPECT() *MockMappingRepositoryMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockMappingRepository) GetAll() ([]editor.Mapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]editor.Mapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockMappingRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockMappingRepository)(nil).GetAll))
}

// SaveAll mocks base method.
func (m *MockMappingRepository) SaveAll(mappings []editor.Mapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAll", mappings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAll indicates an expected call of SaveAll.
func (mr *MockMappingRepositoryMockRecorder) SaveAll(mappings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAll", reflect.TypeOf((*MockMappingRepository)(nil).SaveAll), mappings)
}
