// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/ui/viewmodel (interfaces: ConnectionViewModel)
//
// Generated by this command:
//
//	mockgen -package mocks_viewmodel -destination mocks/viewmodel/connection_viewmodel.go github.com/thomas-marquis/s3-box/internal/ui/viewmodel ConnectionViewModel
//

// Package mocks_viewmodel is a generated GoMock package.
package mocks_viewmodel

import (
	reflect "reflect"

	binding "fyne.io/fyne/v2/data/binding"
	connection "github.com/thomas-marquis/s3-box/internal/connection"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectionViewModel is a mock of ConnectionViewModel interface.
type MockConnectionViewModel struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionViewModelMockRecorder
	isgomock struct{}
}

// MockConnectionViewModelMockRecorder is the mock recorder for MockConnectionViewModel.
type MockConnectionViewModelMockRecorder struct {
	mock *MockConnectionViewModel
}

// NewMockConnectionViewModel creates a new mock instance.
func NewMockConnectionViewModel(ctrl *gomock.Controller) *MockConnectionViewModel {
	mock := &MockConnectionViewModel{ctrl: ctrl}
	mock.recorder = &MockConnectionViewModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionViewModel) EXPECT() *MockConnectionViewModelMockRecorder {
	return m.recorder
}

// Connections mocks base method.
func (m *MockConnectionViewModel) Connections() binding.UntypedList {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connections")
	ret0, _ := ret[0].(binding.UntypedList)
	return ret0
}

// Connections indicates an expected call of Connections.
func (mr *MockConnectionViewModelMockRecorder) Connections() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connections", reflect.TypeOf((*MockConnectionViewModel)(nil).Connections))
}

// Delete mocks base method.
func (m *MockConnectionViewModel) Delete(c *connection.Connection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockConnectionViewModelMockRecorder) Delete(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConnectionViewModel)(nil).Delete), c)
}

// ExportAsJSON mocks base method.
func (m *MockConnectionViewModel) ExportAsJSON() (connection.ConnectionExport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportAsJSON")
	ret0, _ := ret[0].(connection.ConnectionExport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportAsJSON indicates an expected call of ExportAsJSON.
func (mr *MockConnectionViewModelMockRecorder) ExportAsJSON() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportAsJSON", reflect.TypeOf((*MockConnectionViewModel)(nil).ExportAsJSON))
}

// IsReadOnly mocks base method.
func (m *MockConnectionViewModel) IsReadOnly() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsReadOnly")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsReadOnly indicates an expected call of IsReadOnly.
func (mr *MockConnectionViewModelMockRecorder) IsReadOnly() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsReadOnly", reflect.TypeOf((*MockConnectionViewModel)(nil).IsReadOnly))
}

// Save mocks base method.
func (m *MockConnectionViewModel) Save(c connection.Connection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockConnectionViewModelMockRecorder) Save(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockConnectionViewModel)(nil).Save), c)
}

// Select mocks base method.
func (m *MockConnectionViewModel) Select(c *connection.Connection) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", c)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockConnectionViewModelMockRecorder) Select(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockConnectionViewModel)(nil).Select), c)
}
