// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/ui/viewmodel (interfaces: ConnectionViewModel)
//
// Generated by this command:
//
//	mockgen -package mocks_viewmodel -destination mocks/viewmodel/connection_viewmodel.go github.com/thomas-marquis/s3-box/internal/ui/viewmodel ConnectionViewModel
//

// Package mocks_viewmodel is a generated GoMock package.
package mocks_viewmodel

import (
	io "io"
	reflect "reflect"

	binding "fyne.io/fyne/v2/data/binding"
	connection_deck "github.com/thomas-marquis/s3-box/internal/domain/connection_deck"
	gomock "go.uber.org/mock/gomock"
)

// MockConnectionViewModel is a mock of ConnectionViewModel interface.
type MockConnectionViewModel struct {
	ctrl     *gomock.Controller
	recorder *MockConnectionViewModelMockRecorder
	isgomock struct{}
}

// MockConnectionViewModelMockRecorder is the mock recorder for MockConnectionViewModel.
type MockConnectionViewModelMockRecorder struct {
	mock *MockConnectionViewModel
}

// NewMockConnectionViewModel creates a new mock instance.
func NewMockConnectionViewModel(ctrl *gomock.Controller) *MockConnectionViewModel {
	mock := &MockConnectionViewModel{ctrl: ctrl}
	mock.recorder = &MockConnectionViewModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectionViewModel) EXPECT() *MockConnectionViewModelMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockConnectionViewModel) Create(name, accessKey, secretKey, bucket string, options ...connection_deck.ConnectionOption) {
	m.ctrl.T.Helper()
	varargs := []any{name, accessKey, secretKey, bucket}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Create", varargs...)
}

// Create indicates an expected call of Create.
func (mr *MockConnectionViewModelMockRecorder) Create(name, accessKey, secretKey, bucket any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name, accessKey, secretKey, bucket}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockConnectionViewModel)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockConnectionViewModel) Delete(conn *connection_deck.Connection) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", conn)
}

// Delete indicates an expected call of Delete.
func (mr *MockConnectionViewModelMockRecorder) Delete(conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockConnectionViewModel)(nil).Delete), conn)
}

// ErrorMessage mocks base method.
func (m *MockConnectionViewModel) ErrorMessage() binding.String {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorMessage")
	ret0, _ := ret[0].(binding.String)
	return ret0
}

// ErrorMessage indicates an expected call of ErrorMessage.
func (mr *MockConnectionViewModelMockRecorder) ErrorMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorMessage", reflect.TypeOf((*MockConnectionViewModel)(nil).ErrorMessage))
}

// ExportAsJSON mocks base method.
func (m *MockConnectionViewModel) ExportAsJSON(writer io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExportAsJSON", writer)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExportAsJSON indicates an expected call of ExportAsJSON.
func (mr *MockConnectionViewModelMockRecorder) ExportAsJSON(writer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportAsJSON", reflect.TypeOf((*MockConnectionViewModel)(nil).ExportAsJSON), writer)
}

// InfoMessage mocks base method.
func (m *MockConnectionViewModel) InfoMessage() binding.String {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoMessage")
	ret0, _ := ret[0].(binding.String)
	return ret0
}

// InfoMessage indicates an expected call of InfoMessage.
func (mr *MockConnectionViewModelMockRecorder) InfoMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoMessage", reflect.TypeOf((*MockConnectionViewModel)(nil).InfoMessage))
}

// IsLoading mocks base method.
func (m *MockConnectionViewModel) IsLoading() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLoading")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLoading indicates an expected call of IsLoading.
func (mr *MockConnectionViewModelMockRecorder) IsLoading() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLoading", reflect.TypeOf((*MockConnectionViewModel)(nil).IsLoading))
}

// Loading mocks base method.
func (m *MockConnectionViewModel) Loading() binding.Bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Loading")
	ret0, _ := ret[0].(binding.Bool)
	return ret0
}

// Loading indicates an expected call of Loading.
func (mr *MockConnectionViewModelMockRecorder) Loading() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Loading", reflect.TypeOf((*MockConnectionViewModel)(nil).Loading))
}

// Select mocks base method.
func (m *MockConnectionViewModel) Select(conn *connection_deck.Connection) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Select", conn)
}

// Select indicates an expected call of Select.
func (mr *MockConnectionViewModelMockRecorder) Select(conn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockConnectionViewModel)(nil).Select), conn)
}

// Update mocks base method.
func (m *MockConnectionViewModel) Update(connID connection_deck.ConnectionID, options ...connection_deck.ConnectionOption) {
	m.ctrl.T.Helper()
	varargs := []any{connID}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Update", varargs...)
}

// Update indicates an expected call of Update.
func (mr *MockConnectionViewModelMockRecorder) Update(connID any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{connID}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConnectionViewModel)(nil).Update), varargs...)
}
