// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/ui/viewmodel (interfaces: EditorViewModel)
//
// Generated by this command:
//
//	mockgen -package mocks_viewmodel -destination mocks/viewmodel/editor_viewmodel.go github.com/thomas-marquis/s3-box/internal/ui/viewmodel EditorViewModel
//

// Package mocks_viewmodel is a generated GoMock package.
package mocks_viewmodel

import (
	context "context"
	reflect "reflect"

	binding "fyne.io/fyne/v2/data/binding"
	connection_deck "github.com/thomas-marquis/s3-box/internal/domain/connection_deck"
	directory "github.com/thomas-marquis/s3-box/internal/domain/directory"
	viewmodel "github.com/thomas-marquis/s3-box/internal/ui/viewmodel"
	gomock "go.uber.org/mock/gomock"
)

// MockEditorViewModel is a mock of EditorViewModel interface.
type MockEditorViewModel struct {
	ctrl     *gomock.Controller
	recorder *MockEditorViewModelMockRecorder
	isgomock struct{}
}

// MockEditorViewModelMockRecorder is the mock recorder for MockEditorViewModel.
type MockEditorViewModelMockRecorder struct {
	mock *MockEditorViewModel
}

// NewMockEditorViewModel creates a new mock instance.
func NewMockEditorViewModel(ctrl *gomock.Controller) *MockEditorViewModel {
	mock := &MockEditorViewModel{ctrl: ctrl}
	mock.recorder = &MockEditorViewModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditorViewModel) EXPECT() *MockEditorViewModelMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockEditorViewModel) Close(editor *viewmodel.OpenedEditor) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close", editor)
}

// Close indicates an expected call of Close.
func (mr *MockEditorViewModelMockRecorder) Close(editor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockEditorViewModel)(nil).Close), editor)
}

// ErrorMessage mocks base method.
func (m *MockEditorViewModel) ErrorMessage() binding.String {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorMessage")
	ret0, _ := ret[0].(binding.String)
	return ret0
}

// ErrorMessage indicates an expected call of ErrorMessage.
func (mr *MockEditorViewModelMockRecorder) ErrorMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorMessage", reflect.TypeOf((*MockEditorViewModel)(nil).ErrorMessage))
}

// InfoMessage mocks base method.
func (m *MockEditorViewModel) InfoMessage() binding.String {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoMessage")
	ret0, _ := ret[0].(binding.String)
	return ret0
}

// InfoMessage indicates an expected call of InfoMessage.
func (mr *MockEditorViewModelMockRecorder) InfoMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoMessage", reflect.TypeOf((*MockEditorViewModel)(nil).InfoMessage))
}

// IsLoading mocks base method.
func (m *MockEditorViewModel) IsLoading() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLoading")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLoading indicates an expected call of IsLoading.
func (mr *MockEditorViewModelMockRecorder) IsLoading() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLoading", reflect.TypeOf((*MockEditorViewModel)(nil).IsLoading))
}

// IsOpened mocks base method.
func (m *MockEditorViewModel) IsOpened(file *directory.File) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsOpened", file)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsOpened indicates an expected call of IsOpened.
func (mr *MockEditorViewModelMockRecorder) IsOpened(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsOpened", reflect.TypeOf((*MockEditorViewModel)(nil).IsOpened), file)
}

// Loading mocks base method.
func (m *MockEditorViewModel) Loading() binding.Bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Loading")
	ret0, _ := ret[0].(binding.Bool)
	return ret0
}

// Loading indicates an expected call of Loading.
func (mr *MockEditorViewModelMockRecorder) Loading() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Loading", reflect.TypeOf((*MockEditorViewModel)(nil).Loading))
}

// Open mocks base method.
func (m *MockEditorViewModel) Open(ctx context.Context, file *directory.File) (*viewmodel.OpenedEditor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx, file)
	ret0, _ := ret[0].(*viewmodel.OpenedEditor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockEditorViewModelMockRecorder) Open(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockEditorViewModel)(nil).Open), ctx, file)
}

// SelectedConnection mocks base method.
func (m *MockEditorViewModel) SelectedConnection() *connection_deck.Connection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectedConnection")
	ret0, _ := ret[0].(*connection_deck.Connection)
	return ret0
}

// SelectedConnection indicates an expected call of SelectedConnection.
func (mr *MockEditorViewModelMockRecorder) SelectedConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectedConnection", reflect.TypeOf((*MockEditorViewModel)(nil).SelectedConnection))
}
