// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/ui/viewmodel (interfaces: ExplorerViewModel)
//
// Generated by this command:
//
//	mockgen -package mocks_viewmodel -destination mocks/viewmodel/explorer_viewmodel.go github.com/thomas-marquis/s3-box/internal/ui/viewmodel ExplorerViewModel
//

// Package mocks_viewmodel is a generated GoMock package.
package mocks_viewmodel

import (
	reflect "reflect"

	fyne "fyne.io/fyne/v2"
	binding "fyne.io/fyne/v2/data/binding"
	connection_deck "github.com/thomas-marquis/s3-box/internal/domain/connection_deck"
	directory "github.com/thomas-marquis/s3-box/internal/domain/directory"
	viewmodel "github.com/thomas-marquis/s3-box/internal/ui/viewmodel"
	gomock "go.uber.org/mock/gomock"
)

// MockExplorerViewModel is a mock of ExplorerViewModel interface.
type MockExplorerViewModel struct {
	ctrl     *gomock.Controller
	recorder *MockExplorerViewModelMockRecorder
	isgomock struct{}
}

// MockExplorerViewModelMockRecorder is the mock recorder for MockExplorerViewModel.
type MockExplorerViewModelMockRecorder struct {
	mock *MockExplorerViewModel
}

// NewMockExplorerViewModel creates a new mock instance.
func NewMockExplorerViewModel(ctrl *gomock.Controller) *MockExplorerViewModel {
	mock := &MockExplorerViewModel{ctrl: ctrl}
	mock.recorder = &MockExplorerViewModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExplorerViewModel) EXPECT() *MockExplorerViewModelMockRecorder {
	return m.recorder
}

// AbortRename mocks base method.
func (m *MockExplorerViewModel) AbortRename(dir *directory.Directory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortRename", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortRename indicates an expected call of AbortRename.
func (mr *MockExplorerViewModelMockRecorder) AbortRename(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortRename", reflect.TypeOf((*MockExplorerViewModel)(nil).AbortRename), dir)
}

// AddStateListener mocks base method.
func (m *MockExplorerViewModel) AddStateListener(arg0 func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddStateListener", arg0)
}

// AddStateListener indicates an expected call of AddStateListener.
func (mr *MockExplorerViewModelMockRecorder) AddStateListener(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStateListener", reflect.TypeOf((*MockExplorerViewModel)(nil).AddStateListener), arg0)
}

// CreateEmptyDirectory mocks base method.
func (m *MockExplorerViewModel) CreateEmptyDirectory(parent *directory.Directory, name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateEmptyDirectory", parent, name)
}

// CreateEmptyDirectory indicates an expected call of CreateEmptyDirectory.
func (mr *MockExplorerViewModelMockRecorder) CreateEmptyDirectory(parent, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmptyDirectory", reflect.TypeOf((*MockExplorerViewModel)(nil).CreateEmptyDirectory), parent, name)
}

// CreateEmptyFile mocks base method.
func (m *MockExplorerViewModel) CreateEmptyFile(parent *directory.Directory, name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateEmptyFile", parent, name)
}

// CreateEmptyFile indicates an expected call of CreateEmptyFile.
func (mr *MockExplorerViewModelMockRecorder) CreateEmptyFile(parent, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmptyFile", reflect.TypeOf((*MockExplorerViewModel)(nil).CreateEmptyFile), parent, name)
}

// CurrentSelectedConnection mocks base method.
func (m *MockExplorerViewModel) CurrentSelectedConnection() *connection_deck.Connection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentSelectedConnection")
	ret0, _ := ret[0].(*connection_deck.Connection)
	return ret0
}

// CurrentSelectedConnection indicates an expected call of CurrentSelectedConnection.
func (mr *MockExplorerViewModelMockRecorder) CurrentSelectedConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentSelectedConnection", reflect.TypeOf((*MockExplorerViewModel)(nil).CurrentSelectedConnection))
}

// DeleteFile mocks base method.
func (m *MockExplorerViewModel) DeleteFile(file *directory.File) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteFile", file)
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockExplorerViewModelMockRecorder) DeleteFile(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockExplorerViewModel)(nil).DeleteFile), file)
}

// DoUpload mocks base method.
func (m *MockExplorerViewModel) DoUpload(localBasePath string, preview *directory.Preview, strategy directory.MaterializeStrategy) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DoUpload", localBasePath, preview, strategy)
}

// DoUpload indicates an expected call of DoUpload.
func (mr *MockExplorerViewModelMockRecorder) DoUpload(localBasePath, preview, strategy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoUpload", reflect.TypeOf((*MockExplorerViewModel)(nil).DoUpload), localBasePath, preview, strategy)
}

// DownloadFile mocks base method.
func (m *MockExplorerViewModel) DownloadFile(f *directory.File, dest string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DownloadFile", f, dest)
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockExplorerViewModelMockRecorder) DownloadFile(f, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockExplorerViewModel)(nil).DownloadFile), f, dest)
}

// ErrorMessage mocks base method.
func (m *MockExplorerViewModel) ErrorMessage() binding.String {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorMessage")
	ret0, _ := ret[0].(binding.String)
	return ret0
}

// ErrorMessage indicates an expected call of ErrorMessage.
func (mr *MockExplorerViewModelMockRecorder) ErrorMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorMessage", reflect.TypeOf((*MockExplorerViewModel)(nil).ErrorMessage))
}

// InfoMessage mocks base method.
func (m *MockExplorerViewModel) InfoMessage() binding.String {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoMessage")
	ret0, _ := ret[0].(binding.String)
	return ret0
}

// InfoMessage indicates an expected call of InfoMessage.
func (mr *MockExplorerViewModelMockRecorder) InfoMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoMessage", reflect.TypeOf((*MockExplorerViewModel)(nil).InfoMessage))
}

// IsLoading mocks base method.
func (m *MockExplorerViewModel) IsLoading() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLoading")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLoading indicates an expected call of IsLoading.
func (mr *MockExplorerViewModelMockRecorder) IsLoading() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLoading", reflect.TypeOf((*MockExplorerViewModel)(nil).IsLoading))
}

// IsSelectedDirectoryLoading mocks base method.
func (m *MockExplorerViewModel) IsSelectedDirectoryLoading() binding.Bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSelectedDirectoryLoading")
	ret0, _ := ret[0].(binding.Bool)
	return ret0
}

// IsSelectedDirectoryLoading indicates an expected call of IsSelectedDirectoryLoading.
func (mr *MockExplorerViewModelMockRecorder) IsSelectedDirectoryLoading() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSelectedDirectoryLoading", reflect.TypeOf((*MockExplorerViewModel)(nil).IsSelectedDirectoryLoading))
}

// LastDownloadLocation mocks base method.
func (m *MockExplorerViewModel) LastDownloadLocation() fyne.ListableURI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastDownloadLocation")
	ret0, _ := ret[0].(fyne.ListableURI)
	return ret0
}

// LastDownloadLocation indicates an expected call of LastDownloadLocation.
func (mr *MockExplorerViewModelMockRecorder) LastDownloadLocation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastDownloadLocation", reflect.TypeOf((*MockExplorerViewModel)(nil).LastDownloadLocation))
}

// LastUploadLocation mocks base method.
func (m *MockExplorerViewModel) LastUploadLocation() fyne.ListableURI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastUploadLocation")
	ret0, _ := ret[0].(fyne.ListableURI)
	return ret0
}

// LastUploadLocation indicates an expected call of LastUploadLocation.
func (mr *MockExplorerViewModelMockRecorder) LastUploadLocation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastUploadLocation", reflect.TypeOf((*MockExplorerViewModel)(nil).LastUploadLocation))
}

// LoadDirectory mocks base method.
func (m *MockExplorerViewModel) LoadDirectory(dir *directory.Directory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadDirectory", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadDirectory indicates an expected call of LoadDirectory.
func (mr *MockExplorerViewModelMockRecorder) LoadDirectory(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadDirectory", reflect.TypeOf((*MockExplorerViewModel)(nil).LoadDirectory), dir)
}

// Loading mocks base method.
func (m *MockExplorerViewModel) Loading() binding.Bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Loading")
	ret0, _ := ret[0].(binding.Bool)
	return ret0
}

// Loading indicates an expected call of Loading.
func (mr *MockExplorerViewModelMockRecorder) Loading() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Loading", reflect.TypeOf((*MockExplorerViewModel)(nil).Loading))
}

// OnUploadReady mocks base method.
func (m *MockExplorerViewModel) OnUploadReady(arg0 func(viewmodel.UploadPreviewState)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnUploadReady", arg0)
}

// OnUploadReady indicates an expected call of OnUploadReady.
func (mr *MockExplorerViewModelMockRecorder) OnUploadReady(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnUploadReady", reflect.TypeOf((*MockExplorerViewModel)(nil).OnUploadReady), arg0)
}

// PendingUserValidations mocks base method.
func (m *MockExplorerViewModel) PendingUserValidations() <-chan directory.UserValidationAsked {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingUserValidations")
	ret0, _ := ret[0].(<-chan directory.UserValidationAsked)
	return ret0
}

// PendingUserValidations indicates an expected call of PendingUserValidations.
func (mr *MockExplorerViewModelMockRecorder) PendingUserValidations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingUserValidations", reflect.TypeOf((*MockExplorerViewModel)(nil).PendingUserValidations))
}

// PrepareUpload mocks base method.
func (m *MockExplorerViewModel) PrepareUpload(uris []fyne.URI, dir *directory.Directory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareUpload", uris, dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// PrepareUpload indicates an expected call of PrepareUpload.
func (mr *MockExplorerViewModelMockRecorder) PrepareUpload(uris, dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareUpload", reflect.TypeOf((*MockExplorerViewModel)(nil).PrepareUpload), uris, dir)
}

// ReloadDirectory mocks base method.
func (m *MockExplorerViewModel) ReloadDirectory(dir *directory.Directory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadDirectory", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReloadDirectory indicates an expected call of ReloadDirectory.
func (mr *MockExplorerViewModelMockRecorder) ReloadDirectory(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadDirectory", reflect.TypeOf((*MockExplorerViewModel)(nil).ReloadDirectory), dir)
}

// RenameDirectory mocks base method.
func (m *MockExplorerViewModel) RenameDirectory(dir *directory.Directory, newName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenameDirectory", dir, newName)
}

// RenameDirectory indicates an expected call of RenameDirectory.
func (mr *MockExplorerViewModelMockRecorder) RenameDirectory(dir, newName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameDirectory", reflect.TypeOf((*MockExplorerViewModel)(nil).RenameDirectory), dir, newName)
}

// RenameFile mocks base method.
func (m *MockExplorerViewModel) RenameFile(file *directory.File, newName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenameFile", file, newName)
}

// RenameFile indicates an expected call of RenameFile.
func (mr *MockExplorerViewModelMockRecorder) RenameFile(file, newName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameFile", reflect.TypeOf((*MockExplorerViewModel)(nil).RenameFile), file, newName)
}

// ResumeRename mocks base method.
func (m *MockExplorerViewModel) ResumeRename(dir *directory.Directory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeRename", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeRename indicates an expected call of ResumeRename.
func (mr *MockExplorerViewModelMockRecorder) ResumeRename(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeRename", reflect.TypeOf((*MockExplorerViewModel)(nil).ResumeRename), dir)
}

// RollbackRename mocks base method.
func (m *MockExplorerViewModel) RollbackRename(dir *directory.Directory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackRename", dir)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackRename indicates an expected call of RollbackRename.
func (mr *MockExplorerViewModelMockRecorder) RollbackRename(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackRename", reflect.TypeOf((*MockExplorerViewModel)(nil).RollbackRename), dir)
}

// SelectedConnection mocks base method.
func (m *MockExplorerViewModel) SelectedConnection() binding.Untyped {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectedConnection")
	ret0, _ := ret[0].(binding.Untyped)
	return ret0
}

// SelectedConnection indicates an expected call of SelectedConnection.
func (mr *MockExplorerViewModelMockRecorder) SelectedConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectedConnection", reflect.TypeOf((*MockExplorerViewModel)(nil).SelectedConnection))
}

// SelectedDirectory mocks base method.
func (m *MockExplorerViewModel) SelectedDirectory() *directory.Directory {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectedDirectory")
	ret0, _ := ret[0].(*directory.Directory)
	return ret0
}

// SelectedDirectory indicates an expected call of SelectedDirectory.
func (mr *MockExplorerViewModelMockRecorder) SelectedDirectory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectedDirectory", reflect.TypeOf((*MockExplorerViewModel)(nil).SelectedDirectory))
}

// SetSelectedDirectory mocks base method.
func (m *MockExplorerViewModel) SetSelectedDirectory(dir *directory.Directory) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSelectedDirectory", dir)
}

// SetSelectedDirectory indicates an expected call of SetSelectedDirectory.
func (mr *MockExplorerViewModelMockRecorder) SetSelectedDirectory(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSelectedDirectory", reflect.TypeOf((*MockExplorerViewModel)(nil).SetSelectedDirectory), dir)
}

// UpdateLastDownloadLocation mocks base method.
func (m *MockExplorerViewModel) UpdateLastDownloadLocation(filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastDownloadLocation", filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastDownloadLocation indicates an expected call of UpdateLastDownloadLocation.
func (mr *MockExplorerViewModelMockRecorder) UpdateLastDownloadLocation(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastDownloadLocation", reflect.TypeOf((*MockExplorerViewModel)(nil).UpdateLastDownloadLocation), filePath)
}

// UpdateLastUploadLocation mocks base method.
func (m *MockExplorerViewModel) UpdateLastUploadLocation(filePath string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateLastUploadLocation", filePath)
}

// UpdateLastUploadLocation indicates an expected call of UpdateLastUploadLocation.
func (mr *MockExplorerViewModelMockRecorder) UpdateLastUploadLocation(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUploadLocation", reflect.TypeOf((*MockExplorerViewModel)(nil).UpdateLastUploadLocation), filePath)
}

// UploadOne mocks base method.
func (m *MockExplorerViewModel) UploadOne(localPath string, dir *directory.Directory, overwrite bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadOne", localPath, dir, overwrite)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadOne indicates an expected call of UploadOne.
func (mr *MockExplorerViewModelMockRecorder) UploadOne(localPath, dir, overwrite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadOne", reflect.TypeOf((*MockExplorerViewModel)(nil).UploadOne), localPath, dir, overwrite)
}

// Validate mocks base method.
func (m *MockExplorerViewModel) Validate(event directory.UserValidationAsked, validated bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Validate", event, validated)
}

// Validate indicates an expected call of Validate.
func (mr *MockExplorerViewModelMockRecorder) Validate(event, validated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockExplorerViewModel)(nil).Validate), event, validated)
}
