// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/ui/viewmodel (interfaces: ExplorerViewModel)
//
// Generated by this command:
//
//	mockgen -package mocks_viewmodel -destination mocks/viewmodel/explorer_viewmodel.go github.com/thomas-marquis/s3-box/internal/ui/viewmodel ExplorerViewModel
//

// Package mocks_viewmodel is a generated GoMock package.
package mocks_viewmodel

import (
	reflect "reflect"

	fyne "fyne.io/fyne/v2"
	binding "fyne.io/fyne/v2/data/binding"
	connection_deck "github.com/thomas-marquis/s3-box/internal/domain/connection_deck"
	directory "github.com/thomas-marquis/s3-box/internal/domain/directory"
	node "github.com/thomas-marquis/s3-box/internal/ui/node"
	gomock "go.uber.org/mock/gomock"
)

// MockExplorerViewModel is a mock of ExplorerViewModel interface.
type MockExplorerViewModel struct {
	ctrl     *gomock.Controller
	recorder *MockExplorerViewModelMockRecorder
	isgomock struct{}
}

// MockExplorerViewModelMockRecorder is the mock recorder for MockExplorerViewModel.
type MockExplorerViewModelMockRecorder struct {
	mock *MockExplorerViewModel
}

// NewMockExplorerViewModel creates a new mock instance.
func NewMockExplorerViewModel(ctrl *gomock.Controller) *MockExplorerViewModel {
	mock := &MockExplorerViewModel{ctrl: ctrl}
	mock.recorder = &MockExplorerViewModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExplorerViewModel) EXPECT() *MockExplorerViewModelMockRecorder {
	return m.recorder
}

// CreateEmptyDirectory mocks base method.
func (m *MockExplorerViewModel) CreateEmptyDirectory(parent *directory.Directory, name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateEmptyDirectory", parent, name)
}

// CreateEmptyDirectory indicates an expected call of CreateEmptyDirectory.
func (mr *MockExplorerViewModelMockRecorder) CreateEmptyDirectory(parent, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmptyDirectory", reflect.TypeOf((*MockExplorerViewModel)(nil).CreateEmptyDirectory), parent, name)
}

// CreateEmptyFile mocks base method.
func (m *MockExplorerViewModel) CreateEmptyFile(parent *directory.Directory, name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CreateEmptyFile", parent, name)
}

// CreateEmptyFile indicates an expected call of CreateEmptyFile.
func (mr *MockExplorerViewModelMockRecorder) CreateEmptyFile(parent, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmptyFile", reflect.TypeOf((*MockExplorerViewModel)(nil).CreateEmptyFile), parent, name)
}

// CurrentSelectedConnection mocks base method.
func (m *MockExplorerViewModel) CurrentSelectedConnection() *connection_deck.Connection {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentSelectedConnection")
	ret0, _ := ret[0].(*connection_deck.Connection)
	return ret0
}

// CurrentSelectedConnection indicates an expected call of CurrentSelectedConnection.
func (mr *MockExplorerViewModelMockRecorder) CurrentSelectedConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentSelectedConnection", reflect.TypeOf((*MockExplorerViewModel)(nil).CurrentSelectedConnection))
}

// DeleteFile mocks base method.
func (m *MockExplorerViewModel) DeleteFile(file *directory.File) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteFile", file)
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockExplorerViewModelMockRecorder) DeleteFile(file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockExplorerViewModel)(nil).DeleteFile), file)
}

// DownloadFile mocks base method.
func (m *MockExplorerViewModel) DownloadFile(f *directory.File, dest string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DownloadFile", f, dest)
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockExplorerViewModelMockRecorder) DownloadFile(f, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockExplorerViewModel)(nil).DownloadFile), f, dest)
}

// ErrorMessage mocks base method.
func (m *MockExplorerViewModel) ErrorMessage() binding.String {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ErrorMessage")
	ret0, _ := ret[0].(binding.String)
	return ret0
}

// ErrorMessage indicates an expected call of ErrorMessage.
func (mr *MockExplorerViewModelMockRecorder) ErrorMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorMessage", reflect.TypeOf((*MockExplorerViewModel)(nil).ErrorMessage))
}

// GetFileContent mocks base method.
func (m *MockExplorerViewModel) GetFileContent(f *directory.File) (*directory.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileContent", f)
	ret0, _ := ret[0].(*directory.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileContent indicates an expected call of GetFileContent.
func (mr *MockExplorerViewModelMockRecorder) GetFileContent(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileContent", reflect.TypeOf((*MockExplorerViewModel)(nil).GetFileContent), f)
}

// InfoMessage mocks base method.
func (m *MockExplorerViewModel) InfoMessage() binding.String {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoMessage")
	ret0, _ := ret[0].(binding.String)
	return ret0
}

// InfoMessage indicates an expected call of InfoMessage.
func (mr *MockExplorerViewModelMockRecorder) InfoMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoMessage", reflect.TypeOf((*MockExplorerViewModel)(nil).InfoMessage))
}

// IsLoading mocks base method.
func (m *MockExplorerViewModel) IsLoading() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLoading")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLoading indicates an expected call of IsLoading.
func (mr *MockExplorerViewModelMockRecorder) IsLoading() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLoading", reflect.TypeOf((*MockExplorerViewModel)(nil).IsLoading))
}

// LastDownloadLocation mocks base method.
func (m *MockExplorerViewModel) LastDownloadLocation() fyne.ListableURI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastDownloadLocation")
	ret0, _ := ret[0].(fyne.ListableURI)
	return ret0
}

// LastDownloadLocation indicates an expected call of LastDownloadLocation.
func (mr *MockExplorerViewModelMockRecorder) LastDownloadLocation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastDownloadLocation", reflect.TypeOf((*MockExplorerViewModel)(nil).LastDownloadLocation))
}

// LastUploadLocation mocks base method.
func (m *MockExplorerViewModel) LastUploadLocation() fyne.ListableURI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastUploadLocation")
	ret0, _ := ret[0].(fyne.ListableURI)
	return ret0
}

// LastUploadLocation indicates an expected call of LastUploadLocation.
func (mr *MockExplorerViewModelMockRecorder) LastUploadLocation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastUploadLocation", reflect.TypeOf((*MockExplorerViewModel)(nil).LastUploadLocation))
}

// LoadDirectory mocks base method.
func (m *MockExplorerViewModel) LoadDirectory(dirNode node.DirectoryNode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadDirectory", dirNode)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadDirectory indicates an expected call of LoadDirectory.
func (mr *MockExplorerViewModelMockRecorder) LoadDirectory(dirNode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadDirectory", reflect.TypeOf((*MockExplorerViewModel)(nil).LoadDirectory), dirNode)
}

// Loading mocks base method.
func (m *MockExplorerViewModel) Loading() binding.Bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Loading")
	ret0, _ := ret[0].(binding.Bool)
	return ret0
}

// Loading indicates an expected call of Loading.
func (mr *MockExplorerViewModelMockRecorder) Loading() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Loading", reflect.TypeOf((*MockExplorerViewModel)(nil).Loading))
}

// SelectedConnection mocks base method.
func (m *MockExplorerViewModel) SelectedConnection() binding.Untyped {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectedConnection")
	ret0, _ := ret[0].(binding.Untyped)
	return ret0
}

// SelectedConnection indicates an expected call of SelectedConnection.
func (mr *MockExplorerViewModelMockRecorder) SelectedConnection() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectedConnection", reflect.TypeOf((*MockExplorerViewModel)(nil).SelectedConnection))
}

// Tree mocks base method.
func (m *MockExplorerViewModel) Tree() binding.Tree[node.Node] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tree")
	ret0, _ := ret[0].(binding.Tree[node.Node])
	return ret0
}

// Tree indicates an expected call of Tree.
func (mr *MockExplorerViewModelMockRecorder) Tree() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tree", reflect.TypeOf((*MockExplorerViewModel)(nil).Tree))
}

// UpdateLastDownloadLocation mocks base method.
func (m *MockExplorerViewModel) UpdateLastDownloadLocation(filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastDownloadLocation", filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastDownloadLocation indicates an expected call of UpdateLastDownloadLocation.
func (mr *MockExplorerViewModelMockRecorder) UpdateLastDownloadLocation(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastDownloadLocation", reflect.TypeOf((*MockExplorerViewModel)(nil).UpdateLastDownloadLocation), filePath)
}

// UpdateLastUploadLocation mocks base method.
func (m *MockExplorerViewModel) UpdateLastUploadLocation(filePath string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateLastUploadLocation", filePath)
}

// UpdateLastUploadLocation indicates an expected call of UpdateLastUploadLocation.
func (mr *MockExplorerViewModelMockRecorder) UpdateLastUploadLocation(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUploadLocation", reflect.TypeOf((*MockExplorerViewModel)(nil).UpdateLastUploadLocation), filePath)
}

// UploadFile mocks base method.
func (m *MockExplorerViewModel) UploadFile(localPath string, dir *directory.Directory, overwrite bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", localPath, dir, overwrite)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockExplorerViewModelMockRecorder) UploadFile(localPath, dir, overwrite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockExplorerViewModel)(nil).UploadFile), localPath, dir, overwrite)
}
