// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/ui/viewmodel (interfaces: NotificationViewModel)
//
// Generated by this command:
//
//	mockgen -package mocks_viewmodel -destination mocks/viewmodel/notification_viewmodel.go github.com/thomas-marquis/s3-box/internal/ui/viewmodel NotificationViewModel
//

// Package mocks_viewmodel is a generated GoMock package.
package mocks_viewmodel

import (
	reflect "reflect"

	binding "fyne.io/fyne/v2/data/binding"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationViewModel is a mock of NotificationViewModel interface.
type MockNotificationViewModel struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationViewModelMockRecorder
	isgomock struct{}
}

// MockNotificationViewModelMockRecorder is the mock recorder for MockNotificationViewModel.
type MockNotificationViewModelMockRecorder struct {
	mock *MockNotificationViewModel
}

// NewMockNotificationViewModel creates a new mock instance.
func NewMockNotificationViewModel(ctrl *gomock.Controller) *MockNotificationViewModel {
	mock := &MockNotificationViewModel{ctrl: ctrl}
	mock.recorder = &MockNotificationViewModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationViewModel) EXPECT() *MockNotificationViewModelMockRecorder {
	return m.recorder
}

// Notifications mocks base method.
func (m *MockNotificationViewModel) Notifications() binding.StringList {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notifications")
	ret0, _ := ret[0].(binding.StringList)
	return ret0
}

// Notifications indicates an expected call of Notifications.
func (mr *MockNotificationViewModelMockRecorder) Notifications() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notifications", reflect.TypeOf((*MockNotificationViewModel)(nil).Notifications))
}

// SendError mocks base method.
func (m *MockNotificationViewModel) SendError(arg0 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendError", arg0)
}

// SendError indicates an expected call of SendError.
func (mr *MockNotificationViewModelMockRecorder) SendError(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendError", reflect.TypeOf((*MockNotificationViewModel)(nil).SendError), arg0)
}

// SendInfo mocks base method.
func (m *MockNotificationViewModel) SendInfo(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendInfo", arg0)
}

// SendInfo indicates an expected call of SendInfo.
func (mr *MockNotificationViewModelMockRecorder) SendInfo(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendInfo", reflect.TypeOf((*MockNotificationViewModel)(nil).SendInfo), arg0)
}
