// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/ui/viewmodel (interfaces: SettingsViewModel)
//
// Generated by this command:
//
//	mockgen -package mocks_viewmodel -destination mocks/viewmodel/settings_viewmodel.go github.com/thomas-marquis/s3-box/internal/ui/viewmodel SettingsViewModel
//

// Package mocks_viewmodel is a generated GoMock package.
package mocks_viewmodel

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSettingsViewModel is a mock of SettingsViewModel interface.
type MockSettingsViewModel struct {
	ctrl     *gomock.Controller
	recorder *MockSettingsViewModelMockRecorder
	isgomock struct{}
}

// MockSettingsViewModelMockRecorder is the mock recorder for MockSettingsViewModel.
type MockSettingsViewModelMockRecorder struct {
	mock *MockSettingsViewModel
}

// NewMockSettingsViewModel creates a new mock instance.
func NewMockSettingsViewModel(ctrl *gomock.Controller) *MockSettingsViewModel {
	mock := &MockSettingsViewModel{ctrl: ctrl}
	mock.recorder = &MockSettingsViewModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingsViewModel) EXPECT() *MockSettingsViewModelMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockSettingsViewModel) Cancel() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel")
}

// Cancel indicates an expected call of Cancel.
func (mr *MockSettingsViewModelMockRecorder) Cancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockSettingsViewModel)(nil).Cancel))
}

// Save mocks base method.
func (m *MockSettingsViewModel) Save() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Save")
}

// Save indicates an expected call of Save.
func (mr *MockSettingsViewModelMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSettingsViewModel)(nil).Save))
}
