// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/ui/viewmodel (interfaces: TagsViewModel)
//
// Generated by this command:
//
//	mockgen -package mocks_viewmodel -destination mocks/viewmodel/tags_viewmodel.go github.com/thomas-marquis/s3-box/internal/ui/viewmodel TagsViewModel
//

// Package mocks_viewmodel is a generated GoMock package.
package mocks_viewmodel

import (
	reflect "reflect"

	directory "github.com/thomas-marquis/s3-box/internal/domain/directory"
	gomock "go.uber.org/mock/gomock"
)

// MockTagsViewModel is a mock of TagsViewModel interface.
type MockTagsViewModel struct {
	ctrl     *gomock.Controller
	recorder *MockTagsViewModelMockRecorder
	isgomock struct{}
}

// MockTagsViewModelMockRecorder is the mock recorder for MockTagsViewModel.
type MockTagsViewModelMockRecorder struct {
	mock *MockTagsViewModel
}

// NewMockTagsViewModel creates a new mock instance.
func NewMockTagsViewModel(ctrl *gomock.Controller) *MockTagsViewModel {
	mock := &MockTagsViewModel{ctrl: ctrl}
	mock.recorder = &MockTagsViewModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagsViewModel) EXPECT() *MockTagsViewModelMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTagsViewModel) Add(key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockTagsViewModelMockRecorder) Add(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTagsViewModel)(nil).Add), key, value)
}

// Delete mocks base method.
func (m *MockTagsViewModel) Delete(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", key)
}

// Delete indicates an expected call of Delete.
func (mr *MockTagsViewModelMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagsViewModel)(nil).Delete), key)
}

// Save mocks base method.
func (m *MockTagsViewModel) Save() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Save")
}

// Save indicates an expected call of Save.
func (mr *MockTagsViewModelMockRecorder) Save() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockTagsViewModel)(nil).Save))
}

// Select mocks base method.
func (m *MockTagsViewModel) Select(ts *directory.TagSet) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Select", ts)
}

// Select indicates an expected call of Select.
func (mr *MockTagsViewModelMockRecorder) Select(ts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockTagsViewModel)(nil).Select), ts)
}
