// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/domain/notification (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package mocks_notification -destination mocks/notification/repository.go github.com/thomas-marquis/s3-box/internal/domain/notification Repository
//

// Package mocks_notification is a generated GoMock package.
package mocks_notification

import (
	reflect "reflect"

	notification "github.com/thomas-marquis/s3-box/internal/domain/notification"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockRepository) Notify(arg0 notification.Notification) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Notify", arg0)
}

// Notify indicates an expected call of Notify.
func (mr *MockRepositoryMockRecorder) Notify(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockRepository)(nil).Notify), arg0)
}

// NotifyError mocks base method.
func (m *MockRepository) NotifyError(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyError", err)
}

// NotifyError indicates an expected call of NotifyError.
func (mr *MockRepositoryMockRecorder) NotifyError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyError", reflect.TypeOf((*MockRepository)(nil).NotifyError), err)
}

// NotifyInfo mocks base method.
func (m *MockRepository) NotifyInfo(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyInfo", message)
}

// NotifyInfo indicates an expected call of NotifyInfo.
func (mr *MockRepositoryMockRecorder) NotifyInfo(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyInfo", reflect.TypeOf((*MockRepository)(nil).NotifyInfo), message)
}

// Subscribe mocks base method.
func (m *MockRepository) Subscribe(channel chan notification.Notification) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", channel)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockRepositoryMockRecorder) Subscribe(channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockRepository)(nil).Subscribe), channel)
}

// Unsubscribe mocks base method.
func (m *MockRepository) Unsubscribe(channel chan notification.Notification) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", channel)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockRepositoryMockRecorder) Unsubscribe(channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockRepository)(nil).Unsubscribe), channel)
}
