// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/infrastructure/s3/s3client (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -package mocks_s3client -destination mocks/infrastructure/s3client.go github.com/thomas-marquis/s3-box/internal/infrastructure/s3/s3client Client
//

// Package mocks_s3client is a generated GoMock package.
package mocks_s3client

import (
	context "context"
	io "io"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	types "github.com/aws/aws-sdk-go-v2/service/s3/types"
	s3client "github.com/thomas-marquis/s3-box/internal/infrastructure/s3/s3client"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockClient) DeleteObject(ctx context.Context, key string, opts ...s3client.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteObject", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockClientMockRecorder) DeleteObject(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockClient)(nil).DeleteObject), varargs...)
}

// Download mocks base method.
func (m *MockClient) Download(ctx context.Context, key string, writer io.WriterAt, opts ...s3client.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, writer}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Download", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Download indicates an expected call of Download.
func (mr *MockClientMockRecorder) Download(ctx, key, writer any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, writer}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockClient)(nil).Download), varargs...)
}

// DownloadDirectory mocks base method.
func (m *MockClient) DownloadDirectory(ctx context.Context, keyPrefix, dest string, opts ...s3client.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, keyPrefix, dest}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DownloadDirectory", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadDirectory indicates an expected call of DownloadDirectory.
func (mr *MockClientMockRecorder) DownloadDirectory(ctx, keyPrefix, dest any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, keyPrefix, dest}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadDirectory", reflect.TypeOf((*MockClient)(nil).DownloadDirectory), varargs...)
}

// GetObject mocks base method.
func (m *MockClient) GetObject(ctx context.Context, key string, opts ...s3client.Option) (*s3.GetObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObject", varargs...)
	ret0, _ := ret[0].(*s3.GetObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObject indicates an expected call of GetObject.
func (mr *MockClientMockRecorder) GetObject(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObject", reflect.TypeOf((*MockClient)(nil).GetObject), varargs...)
}

// GetObjectGrants mocks base method.
func (m *MockClient) GetObjectGrants(ctx context.Context, key string, opts ...s3client.Option) (s3client.Grants, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObjectGrants", varargs...)
	ret0, _ := ret[0].(s3client.Grants)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectGrants indicates an expected call of GetObjectGrants.
func (mr *MockClientMockRecorder) GetObjectGrants(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectGrants", reflect.TypeOf((*MockClient)(nil).GetObjectGrants), varargs...)
}

// GetObjectTagging mocks base method.
func (m *MockClient) GetObjectTagging(ctx context.Context, key string, opts ...s3client.Option) (*s3.GetObjectTaggingOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetObjectTagging", varargs...)
	ret0, _ := ret[0].(*s3.GetObjectTaggingOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectTagging indicates an expected call of GetObjectTagging.
func (mr *MockClientMockRecorder) GetObjectTagging(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectTagging", reflect.TypeOf((*MockClient)(nil).GetObjectTagging), varargs...)
}

// ListObjects mocks base method.
func (m *MockClient) ListObjects(ctx context.Context, prefix string, recursive bool, opts ...s3client.Option) (s3client.ListObjectsResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, prefix, recursive}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListObjects", varargs...)
	ret0, _ := ret[0].(s3client.ListObjectsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListObjects indicates an expected call of ListObjects.
func (mr *MockClientMockRecorder) ListObjects(ctx, prefix, recursive any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, prefix, recursive}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjects", reflect.TypeOf((*MockClient)(nil).ListObjects), varargs...)
}

// ListObjectsWithCallback mocks base method.
func (m *MockClient) ListObjectsWithCallback(ctx context.Context, prefix string, recursive bool, callback func(*s3.ListObjectsV2Output) error, opts ...s3client.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, prefix, recursive, callback}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListObjectsWithCallback", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListObjectsWithCallback indicates an expected call of ListObjectsWithCallback.
func (mr *MockClientMockRecorder) ListObjectsWithCallback(ctx, prefix, recursive, callback any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, prefix, recursive, callback}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListObjectsWithCallback", reflect.TypeOf((*MockClient)(nil).ListObjectsWithCallback), varargs...)
}

// PutObject mocks base method.
func (m *MockClient) PutObject(ctx context.Context, key string, body io.Reader, opts ...s3client.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutObject", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutObject indicates an expected call of PutObject.
func (mr *MockClientMockRecorder) PutObject(ctx, key, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObject", reflect.TypeOf((*MockClient)(nil).PutObject), varargs...)
}

// PutObjectTagging mocks base method.
func (m *MockClient) PutObjectTagging(ctx context.Context, key string, tags []types.Tag, opts ...s3client.Option) (*s3.PutObjectTaggingOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, tags}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutObjectTagging", varargs...)
	ret0, _ := ret[0].(*s3.PutObjectTaggingOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutObjectTagging indicates an expected call of PutObjectTagging.
func (mr *MockClientMockRecorder) PutObjectTagging(ctx, key, tags any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, tags}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutObjectTagging", reflect.TypeOf((*MockClient)(nil).PutObjectTagging), varargs...)
}

// RenameObject mocks base method.
func (m *MockClient) RenameObject(ctx context.Context, oldKey, newKey string, opts ...s3client.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, oldKey, newKey}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RenameObject", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenameObject indicates an expected call of RenameObject.
func (mr *MockClientMockRecorder) RenameObject(ctx, oldKey, newKey any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, oldKey, newKey}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameObject", reflect.TypeOf((*MockClient)(nil).RenameObject), varargs...)
}

// Upload mocks base method.
func (m *MockClient) Upload(ctx context.Context, key string, body io.Reader, opts ...s3client.Option) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, body}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Upload", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockClientMockRecorder) Upload(ctx, key, body any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, body}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockClient)(nil).Upload), varargs...)
}
