// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/domain/directory (interfaces: FileContent)
//
// Generated by this command:
//
//	mockgen -package mocks_directory -destination mocks/directory/content.go github.com/thomas-marquis/s3-box/internal/domain/directory FileContent
//

// Package mocks_directory is a generated GoMock package.
package mocks_directory

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileContent is a mock of FileContent interface.
type MockFileContent struct {
	ctrl     *gomock.Controller
	recorder *MockFileContentMockRecorder
	isgomock struct{}
}

// MockFileContentMockRecorder is the mock recorder for MockFileContent.
type MockFileContentMockRecorder struct {
	mock *MockFileContent
}

// NewMockFileContent creates a new mock instance.
func NewMockFileContent(ctrl *gomock.Controller) *MockFileContent {
	mock := &MockFileContent{ctrl: ctrl}
	mock.recorder = &MockFileContentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileContent) EXPECT() *MockFileContentMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockFileContent) Cancel() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel")
}

// Cancel indicates an expected call of Cancel.
func (mr *MockFileContentMockRecorder) Cancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockFileContent)(nil).Cancel))
}

// Close mocks base method.
func (m *MockFileContent) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockFileContentMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockFileContent)(nil).Close))
}

// Read mocks base method.
func (m *MockFileContent) Read(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockFileContentMockRecorder) Read(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockFileContent)(nil).Read), p)
}

// Seek mocks base method.
func (m *MockFileContent) Seek(offset int64, whence int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seek", offset, whence)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seek indicates an expected call of Seek.
func (mr *MockFileContentMockRecorder) Seek(offset, whence any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seek", reflect.TypeOf((*MockFileContent)(nil).Seek), offset, whence)
}

// Write mocks base method.
func (m *MockFileContent) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *MockFileContentMockRecorder) Write(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockFileContent)(nil).Write), p)
}
