// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/domain/directory (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package mocks_explorer -destination mocks/directory/repository.go github.com/thomas-marquis/s3-box/internal/domain/directory Repository
//

// Package mocks_explorer is a generated GoMock package.
package mocks_explorer

import (
	context "context"
	reflect "reflect"

	connection_deck "github.com/thomas-marquis/s3-box/internal/domain/connection_deck"
	directory "github.com/thomas-marquis/s3-box/internal/domain/directory"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetByPath mocks base method.
func (m *MockRepository) GetByPath(ctx context.Context, connID connection_deck.ConnectionID, path directory.Path) (*directory.Directory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPath", ctx, connID, path)
	ret0, _ := ret[0].(*directory.Directory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPath indicates an expected call of GetByPath.
func (mr *MockRepositoryMockRecorder) GetByPath(ctx, connID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPath", reflect.TypeOf((*MockRepository)(nil).GetByPath), ctx, connID, path)
}

// GetFileContent mocks base method.
func (m *MockRepository) GetFileContent(ctx context.Context, connID connection_deck.ConnectionID, file *directory.File) (*directory.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileContent", ctx, connID, file)
	ret0, _ := ret[0].(*directory.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileContent indicates an expected call of GetFileContent.
func (mr *MockRepositoryMockRecorder) GetFileContent(ctx, connID, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileContent", reflect.TypeOf((*MockRepository)(nil).GetFileContent), ctx, connID, file)
}
