// Code generated by MockGen. DO NOT EDIT.
// Source: fyne.io/fyne/v2 (interfaces: Preferences)
//
// Generated by this command:
//
//	mockgen -package mocks_fyne -destination mocks/fyne/preferences.go fyne.io/fyne/v2 Preferences
//

// Package mocks_fyne is a generated GoMock package.
package mocks_fyne

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPreferences is a mock of Preferences interface.
type MockPreferences struct {
	ctrl     *gomock.Controller
	recorder *MockPreferencesMockRecorder
	isgomock struct{}
}

// MockPreferencesMockRecorder is the mock recorder for MockPreferences.
type MockPreferencesMockRecorder struct {
	mock *MockPreferences
}

// NewMockPreferences creates a new mock instance.
func NewMockPreferences(ctrl *gomock.Controller) *MockPreferences {
	mock := &MockPreferences{ctrl: ctrl}
	mock.recorder = &MockPreferencesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreferences) EXPECT() *MockPreferencesMockRecorder {
	return m.recorder
}

// AddChangeListener mocks base method.
func (m *MockPreferences) AddChangeListener(arg0 func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddChangeListener", arg0)
}

// AddChangeListener indicates an expected call of AddChangeListener.
func (mr *MockPreferencesMockRecorder) AddChangeListener(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChangeListener", reflect.TypeOf((*MockPreferences)(nil).AddChangeListener), arg0)
}

// Bool mocks base method.
func (m *MockPreferences) Bool(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bool", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Bool indicates an expected call of Bool.
func (mr *MockPreferencesMockRecorder) Bool(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bool", reflect.TypeOf((*MockPreferences)(nil).Bool), key)
}

// BoolList mocks base method.
func (m *MockPreferences) BoolList(key string) []bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BoolList", key)
	ret0, _ := ret[0].([]bool)
	return ret0
}

// BoolList indicates an expected call of BoolList.
func (mr *MockPreferencesMockRecorder) BoolList(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BoolList", reflect.TypeOf((*MockPreferences)(nil).BoolList), key)
}

// BoolListWithFallback mocks base method.
func (m *MockPreferences) BoolListWithFallback(key string, fallback []bool) []bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BoolListWithFallback", key, fallback)
	ret0, _ := ret[0].([]bool)
	return ret0
}

// BoolListWithFallback indicates an expected call of BoolListWithFallback.
func (mr *MockPreferencesMockRecorder) BoolListWithFallback(key, fallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BoolListWithFallback", reflect.TypeOf((*MockPreferences)(nil).BoolListWithFallback), key, fallback)
}

// BoolWithFallback mocks base method.
func (m *MockPreferences) BoolWithFallback(key string, fallback bool) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BoolWithFallback", key, fallback)
	ret0, _ := ret[0].(bool)
	return ret0
}

// BoolWithFallback indicates an expected call of BoolWithFallback.
func (mr *MockPreferencesMockRecorder) BoolWithFallback(key, fallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BoolWithFallback", reflect.TypeOf((*MockPreferences)(nil).BoolWithFallback), key, fallback)
}

// ChangeListeners mocks base method.
func (m *MockPreferences) ChangeListeners() []func() {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeListeners")
	ret0, _ := ret[0].([]func())
	return ret0
}

// ChangeListeners indicates an expected call of ChangeListeners.
func (mr *MockPreferencesMockRecorder) ChangeListeners() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeListeners", reflect.TypeOf((*MockPreferences)(nil).ChangeListeners))
}

// Float mocks base method.
func (m *MockPreferences) Float(key string) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Float", key)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Float indicates an expected call of Float.
func (mr *MockPreferencesMockRecorder) Float(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Float", reflect.TypeOf((*MockPreferences)(nil).Float), key)
}

// FloatList mocks base method.
func (m *MockPreferences) FloatList(key string) []float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FloatList", key)
	ret0, _ := ret[0].([]float64)
	return ret0
}

// FloatList indicates an expected call of FloatList.
func (mr *MockPreferencesMockRecorder) FloatList(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FloatList", reflect.TypeOf((*MockPreferences)(nil).FloatList), key)
}

// FloatListWithFallback mocks base method.
func (m *MockPreferences) FloatListWithFallback(key string, fallback []float64) []float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FloatListWithFallback", key, fallback)
	ret0, _ := ret[0].([]float64)
	return ret0
}

// FloatListWithFallback indicates an expected call of FloatListWithFallback.
func (mr *MockPreferencesMockRecorder) FloatListWithFallback(key, fallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FloatListWithFallback", reflect.TypeOf((*MockPreferences)(nil).FloatListWithFallback), key, fallback)
}

// FloatWithFallback mocks base method.
func (m *MockPreferences) FloatWithFallback(key string, fallback float64) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FloatWithFallback", key, fallback)
	ret0, _ := ret[0].(float64)
	return ret0
}

// FloatWithFallback indicates an expected call of FloatWithFallback.
func (mr *MockPreferencesMockRecorder) FloatWithFallback(key, fallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FloatWithFallback", reflect.TypeOf((*MockPreferences)(nil).FloatWithFallback), key, fallback)
}

// Int mocks base method.
func (m *MockPreferences) Int(key string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Int", key)
	ret0, _ := ret[0].(int)
	return ret0
}

// Int indicates an expected call of Int.
func (mr *MockPreferencesMockRecorder) Int(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Int", reflect.TypeOf((*MockPreferences)(nil).Int), key)
}

// IntList mocks base method.
func (m *MockPreferences) IntList(key string) []int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntList", key)
	ret0, _ := ret[0].([]int)
	return ret0
}

// IntList indicates an expected call of IntList.
func (mr *MockPreferencesMockRecorder) IntList(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntList", reflect.TypeOf((*MockPreferences)(nil).IntList), key)
}

// IntListWithFallback mocks base method.
func (m *MockPreferences) IntListWithFallback(key string, fallback []int) []int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntListWithFallback", key, fallback)
	ret0, _ := ret[0].([]int)
	return ret0
}

// IntListWithFallback indicates an expected call of IntListWithFallback.
func (mr *MockPreferencesMockRecorder) IntListWithFallback(key, fallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntListWithFallback", reflect.TypeOf((*MockPreferences)(nil).IntListWithFallback), key, fallback)
}

// IntWithFallback mocks base method.
func (m *MockPreferences) IntWithFallback(key string, fallback int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntWithFallback", key, fallback)
	ret0, _ := ret[0].(int)
	return ret0
}

// IntWithFallback indicates an expected call of IntWithFallback.
func (mr *MockPreferencesMockRecorder) IntWithFallback(key, fallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntWithFallback", reflect.TypeOf((*MockPreferences)(nil).IntWithFallback), key, fallback)
}

// RemoveValue mocks base method.
func (m *MockPreferences) RemoveValue(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveValue", key)
}

// RemoveValue indicates an expected call of RemoveValue.
func (mr *MockPreferencesMockRecorder) RemoveValue(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveValue", reflect.TypeOf((*MockPreferences)(nil).RemoveValue), key)
}

// SetBool mocks base method.
func (m *MockPreferences) SetBool(key string, value bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBool", key, value)
}

// SetBool indicates an expected call of SetBool.
func (mr *MockPreferencesMockRecorder) SetBool(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBool", reflect.TypeOf((*MockPreferences)(nil).SetBool), key, value)
}

// SetBoolList mocks base method.
func (m *MockPreferences) SetBoolList(key string, value []bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBoolList", key, value)
}

// SetBoolList indicates an expected call of SetBoolList.
func (mr *MockPreferencesMockRecorder) SetBoolList(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBoolList", reflect.TypeOf((*MockPreferences)(nil).SetBoolList), key, value)
}

// SetFloat mocks base method.
func (m *MockPreferences) SetFloat(key string, value float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFloat", key, value)
}

// SetFloat indicates an expected call of SetFloat.
func (mr *MockPreferencesMockRecorder) SetFloat(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFloat", reflect.TypeOf((*MockPreferences)(nil).SetFloat), key, value)
}

// SetFloatList mocks base method.
func (m *MockPreferences) SetFloatList(key string, value []float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFloatList", key, value)
}

// SetFloatList indicates an expected call of SetFloatList.
func (mr *MockPreferencesMockRecorder) SetFloatList(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFloatList", reflect.TypeOf((*MockPreferences)(nil).SetFloatList), key, value)
}

// SetInt mocks base method.
func (m *MockPreferences) SetInt(key string, value int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetInt", key, value)
}

// SetInt indicates an expected call of SetInt.
func (mr *MockPreferencesMockRecorder) SetInt(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInt", reflect.TypeOf((*MockPreferences)(nil).SetInt), key, value)
}

// SetIntList mocks base method.
func (m *MockPreferences) SetIntList(key string, value []int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetIntList", key, value)
}

// SetIntList indicates an expected call of SetIntList.
func (mr *MockPreferencesMockRecorder) SetIntList(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIntList", reflect.TypeOf((*MockPreferences)(nil).SetIntList), key, value)
}

// SetString mocks base method.
func (m *MockPreferences) SetString(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetString", key, value)
}

// SetString indicates an expected call of SetString.
func (mr *MockPreferencesMockRecorder) SetString(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetString", reflect.TypeOf((*MockPreferences)(nil).SetString), key, value)
}

// SetStringList mocks base method.
func (m *MockPreferences) SetStringList(key string, value []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStringList", key, value)
}

// SetStringList indicates an expected call of SetStringList.
func (mr *MockPreferencesMockRecorder) SetStringList(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStringList", reflect.TypeOf((*MockPreferences)(nil).SetStringList), key, value)
}

// String mocks base method.
func (m *MockPreferences) String(key string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String", key)
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockPreferencesMockRecorder) String(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockPreferences)(nil).String), key)
}

// StringList mocks base method.
func (m *MockPreferences) StringList(key string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringList", key)
	ret0, _ := ret[0].([]string)
	return ret0
}

// StringList indicates an expected call of StringList.
func (mr *MockPreferencesMockRecorder) StringList(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringList", reflect.TypeOf((*MockPreferences)(nil).StringList), key)
}

// StringListWithFallback mocks base method.
func (m *MockPreferences) StringListWithFallback(key string, fallback []string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringListWithFallback", key, fallback)
	ret0, _ := ret[0].([]string)
	return ret0
}

// StringListWithFallback indicates an expected call of StringListWithFallback.
func (mr *MockPreferencesMockRecorder) StringListWithFallback(key, fallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringListWithFallback", reflect.TypeOf((*MockPreferences)(nil).StringListWithFallback), key, fallback)
}

// StringWithFallback mocks base method.
func (m *MockPreferences) StringWithFallback(key, fallback string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringWithFallback", key, fallback)
	ret0, _ := ret[0].(string)
	return ret0
}

// StringWithFallback indicates an expected call of StringWithFallback.
func (mr *MockPreferencesMockRecorder) StringWithFallback(key, fallback any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringWithFallback", reflect.TypeOf((*MockPreferences)(nil).StringWithFallback), key, fallback)
}
