// Code generated by MockGen. DO NOT EDIT.
// Source: fyne.io/fyne/v2 (interfaces: Window)
//
// Generated by this command:
//
//	mockgen -package mocks_fyne -destination mocks/fyne/window.go fyne.io/fyne/v2 Window
//

// Package mocks_fyne is a generated GoMock package.
package mocks_fyne

import (
	reflect "reflect"

	fyne "fyne.io/fyne/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockWindow is a mock of Window interface.
type MockWindow struct {
	ctrl     *gomock.Controller
	recorder *MockWindowMockRecorder
	isgomock struct{}
}

// MockWindowMockRecorder is the mock recorder for MockWindow.
type MockWindowMockRecorder struct {
	mock *MockWindow
}

// NewMockWindow creates a new mock instance.
func NewMockWindow(ctrl *gomock.Controller) *MockWindow {
	mock := &MockWindow{ctrl: ctrl}
	mock.recorder = &MockWindowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWindow) EXPECT() *MockWindowMockRecorder {
	return m.recorder
}

// Canvas mocks base method.
func (m *MockWindow) Canvas() fyne.Canvas {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Canvas")
	ret0, _ := ret[0].(fyne.Canvas)
	return ret0
}

// Canvas indicates an expected call of Canvas.
func (mr *MockWindowMockRecorder) Canvas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Canvas", reflect.TypeOf((*MockWindow)(nil).Canvas))
}

// CenterOnScreen mocks base method.
func (m *MockWindow) CenterOnScreen() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CenterOnScreen")
}

// CenterOnScreen indicates an expected call of CenterOnScreen.
func (mr *MockWindowMockRecorder) CenterOnScreen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CenterOnScreen", reflect.TypeOf((*MockWindow)(nil).CenterOnScreen))
}

// Clipboard mocks base method.
func (m *MockWindow) Clipboard() fyne.Clipboard {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clipboard")
	ret0, _ := ret[0].(fyne.Clipboard)
	return ret0
}

// Clipboard indicates an expected call of Clipboard.
func (mr *MockWindowMockRecorder) Clipboard() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clipboard", reflect.TypeOf((*MockWindow)(nil).Clipboard))
}

// Close mocks base method.
func (m *MockWindow) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockWindowMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWindow)(nil).Close))
}

// Content mocks base method.
func (m *MockWindow) Content() fyne.CanvasObject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Content")
	ret0, _ := ret[0].(fyne.CanvasObject)
	return ret0
}

// Content indicates an expected call of Content.
func (mr *MockWindowMockRecorder) Content() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Content", reflect.TypeOf((*MockWindow)(nil).Content))
}

// FixedSize mocks base method.
func (m *MockWindow) FixedSize() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FixedSize")
	ret0, _ := ret[0].(bool)
	return ret0
}

// FixedSize indicates an expected call of FixedSize.
func (mr *MockWindowMockRecorder) FixedSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FixedSize", reflect.TypeOf((*MockWindow)(nil).FixedSize))
}

// FullScreen mocks base method.
func (m *MockWindow) FullScreen() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FullScreen")
	ret0, _ := ret[0].(bool)
	return ret0
}

// FullScreen indicates an expected call of FullScreen.
func (mr *MockWindowMockRecorder) FullScreen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FullScreen", reflect.TypeOf((*MockWindow)(nil).FullScreen))
}

// Hide mocks base method.
func (m *MockWindow) Hide() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Hide")
}

// Hide indicates an expected call of Hide.
func (mr *MockWindowMockRecorder) Hide() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hide", reflect.TypeOf((*MockWindow)(nil).Hide))
}

// Icon mocks base method.
func (m *MockWindow) Icon() fyne.Resource {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Icon")
	ret0, _ := ret[0].(fyne.Resource)
	return ret0
}

// Icon indicates an expected call of Icon.
func (mr *MockWindowMockRecorder) Icon() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Icon", reflect.TypeOf((*MockWindow)(nil).Icon))
}

// MainMenu mocks base method.
func (m *MockWindow) MainMenu() *fyne.MainMenu {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MainMenu")
	ret0, _ := ret[0].(*fyne.MainMenu)
	return ret0
}

// MainMenu indicates an expected call of MainMenu.
func (mr *MockWindowMockRecorder) MainMenu() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MainMenu", reflect.TypeOf((*MockWindow)(nil).MainMenu))
}

// Padded mocks base method.
func (m *MockWindow) Padded() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Padded")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Padded indicates an expected call of Padded.
func (mr *MockWindowMockRecorder) Padded() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Padded", reflect.TypeOf((*MockWindow)(nil).Padded))
}

// RequestFocus mocks base method.
func (m *MockWindow) RequestFocus() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestFocus")
}

// RequestFocus indicates an expected call of RequestFocus.
func (mr *MockWindowMockRecorder) RequestFocus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestFocus", reflect.TypeOf((*MockWindow)(nil).RequestFocus))
}

// Resize mocks base method.
func (m *MockWindow) Resize(arg0 fyne.Size) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Resize", arg0)
}

// Resize indicates an expected call of Resize.
func (mr *MockWindowMockRecorder) Resize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockWindow)(nil).Resize), arg0)
}

// SetCloseIntercept mocks base method.
func (m *MockWindow) SetCloseIntercept(arg0 func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCloseIntercept", arg0)
}

// SetCloseIntercept indicates an expected call of SetCloseIntercept.
func (mr *MockWindowMockRecorder) SetCloseIntercept(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCloseIntercept", reflect.TypeOf((*MockWindow)(nil).SetCloseIntercept), arg0)
}

// SetContent mocks base method.
func (m *MockWindow) SetContent(arg0 fyne.CanvasObject) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContent", arg0)
}

// SetContent indicates an expected call of SetContent.
func (mr *MockWindowMockRecorder) SetContent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContent", reflect.TypeOf((*MockWindow)(nil).SetContent), arg0)
}

// SetFixedSize mocks base method.
func (m *MockWindow) SetFixedSize(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFixedSize", arg0)
}

// SetFixedSize indicates an expected call of SetFixedSize.
func (mr *MockWindowMockRecorder) SetFixedSize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFixedSize", reflect.TypeOf((*MockWindow)(nil).SetFixedSize), arg0)
}

// SetFullScreen mocks base method.
func (m *MockWindow) SetFullScreen(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFullScreen", arg0)
}

// SetFullScreen indicates an expected call of SetFullScreen.
func (mr *MockWindowMockRecorder) SetFullScreen(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFullScreen", reflect.TypeOf((*MockWindow)(nil).SetFullScreen), arg0)
}

// SetIcon mocks base method.
func (m *MockWindow) SetIcon(arg0 fyne.Resource) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetIcon", arg0)
}

// SetIcon indicates an expected call of SetIcon.
func (mr *MockWindowMockRecorder) SetIcon(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIcon", reflect.TypeOf((*MockWindow)(nil).SetIcon), arg0)
}

// SetMainMenu mocks base method.
func (m *MockWindow) SetMainMenu(arg0 *fyne.MainMenu) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMainMenu", arg0)
}

// SetMainMenu indicates an expected call of SetMainMenu.
func (mr *MockWindowMockRecorder) SetMainMenu(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMainMenu", reflect.TypeOf((*MockWindow)(nil).SetMainMenu), arg0)
}

// SetMaster mocks base method.
func (m *MockWindow) SetMaster() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMaster")
}

// SetMaster indicates an expected call of SetMaster.
func (mr *MockWindowMockRecorder) SetMaster() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaster", reflect.TypeOf((*MockWindow)(nil).SetMaster))
}

// SetOnClosed mocks base method.
func (m *MockWindow) SetOnClosed(arg0 func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnClosed", arg0)
}

// SetOnClosed indicates an expected call of SetOnClosed.
func (mr *MockWindowMockRecorder) SetOnClosed(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnClosed", reflect.TypeOf((*MockWindow)(nil).SetOnClosed), arg0)
}

// SetOnDropped mocks base method.
func (m *MockWindow) SetOnDropped(arg0 func(fyne.Position, []fyne.URI)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnDropped", arg0)
}

// SetOnDropped indicates an expected call of SetOnDropped.
func (mr *MockWindowMockRecorder) SetOnDropped(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnDropped", reflect.TypeOf((*MockWindow)(nil).SetOnDropped), arg0)
}

// SetPadded mocks base method.
func (m *MockWindow) SetPadded(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPadded", arg0)
}

// SetPadded indicates an expected call of SetPadded.
func (mr *MockWindowMockRecorder) SetPadded(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPadded", reflect.TypeOf((*MockWindow)(nil).SetPadded), arg0)
}

// SetTitle mocks base method.
func (m *MockWindow) SetTitle(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTitle", arg0)
}

// SetTitle indicates an expected call of SetTitle.
func (mr *MockWindowMockRecorder) SetTitle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTitle", reflect.TypeOf((*MockWindow)(nil).SetTitle), arg0)
}

// Show mocks base method.
func (m *MockWindow) Show() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Show")
}

// Show indicates an expected call of Show.
func (mr *MockWindowMockRecorder) Show() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Show", reflect.TypeOf((*MockWindow)(nil).Show))
}

// ShowAndRun mocks base method.
func (m *MockWindow) ShowAndRun() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ShowAndRun")
}

// ShowAndRun indicates an expected call of ShowAndRun.
func (mr *MockWindowMockRecorder) ShowAndRun() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowAndRun", reflect.TypeOf((*MockWindow)(nil).ShowAndRun))
}

// Title mocks base method.
func (m *MockWindow) Title() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Title")
	ret0, _ := ret[0].(string)
	return ret0
}

// Title indicates an expected call of Title.
func (mr *MockWindowMockRecorder) Title() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Title", reflect.TypeOf((*MockWindow)(nil).Title))
}
