// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/domain/shared/event (interfaces: Bus)
//
// Generated by this command:
//
//	mockgen -package mocks_event -destination mocks/event/bus.go github.com/thomas-marquis/s3-box/internal/domain/shared/event Bus
//

// Package mocks_event is a generated GoMock package.
package mocks_event

import (
	reflect "reflect"

	event "github.com/thomas-marquis/s3-box/internal/domain/shared/event"
	gomock "go.uber.org/mock/gomock"
)

// MockBus is a mock of Bus interface.
type MockBus struct {
	ctrl     *gomock.Controller
	recorder *MockBusMockRecorder
	isgomock struct{}
}

// MockBusMockRecorder is the mock recorder for MockBus.
type MockBusMockRecorder struct {
	mock *MockBus
}

// NewMockBus creates a new mock instance.
func NewMockBus(ctrl *gomock.Controller) *MockBus {
	mock := &MockBus{ctrl: ctrl}
	mock.recorder = &MockBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBus) EXPECT() *MockBusMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockBus) Publish(evt event.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", evt)
}

// Publish indicates an expected call of Publish.
func (mr *MockBusMockRecorder) Publish(evt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockBus)(nil).Publish), evt)
}

// Subscribe mocks base method.
func (m *MockBus) Subscribe(eventTypes ...event.Type) <-chan event.Event {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range eventTypes {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Subscribe", varargs...)
	ret0, _ := ret[0].(<-chan event.Event)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockBusMockRecorder) Subscribe(eventTypes ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockBus)(nil).Subscribe), eventTypes...)
}
