name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag. Format: vX.Y.Z'
        required: true
        type: string

env:
  BASE_APP_NAME: "S3Box"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.x'
          cache: true

      - name: Setup environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev libc6

      - name: Install dependencies
        run: |
          go get .
          go install fyne.io/fyne/v2/cmd/fyne@latest
          go install github.com/fyne-io/fyne-cross@latest

      - name: Test
        run: go test -v ./...

      - name: Get semver
        id: get_version
        shell: bash
        run: |
          VERSION="${{ github.event.inputs.version || github.ref_name }}"
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
          echo "tag=${VERSION}" >> $GITHUB_OUTPUT

      - name: Package for Linux
        run: |
          fyne-cross linux -arch=amd64 -name ${{ env.BASE_APP_NAME }} -icon resources/logo-wbg.png -app-version ${{ steps.get_version.outputs.version }} -app-id fr.scalde.s3box

      - name: Package for Windows
        run: |
          fyne-cross windows -arch=amd64 -name ${{ env.BASE_APP_NAME }} -icon resources/logo-wbg.png -app-version ${{ steps.get_version.outputs.version }} -app-id fr.scalde.s3box

      - name: Upload Linux binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          make_latest: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fyne-cross/dist/linux-amd64/${{ env.BASE_APP_NAME }}.tar.xz
          asset_name: ${{ env.BASE_APP_NAME }}-linux-amd64-${{ steps.get_version.outputs.tag }}.tar.xz
          tag: ${{ steps.get_version.outputs.tag }}
          overwrite: true
          body: "New release ${{ steps.get_version.outputs.tag }}"
          draft: false
          prerelease: false

      - name: Upload Windows binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          make_latest: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fyne-cross/dist/windows-amd64/${{ env.BASE_APP_NAME }}.zip
          asset_name: ${{ env.BASE_APP_NAME }}-windows-amd64-${{ steps.get_version.outputs.tag }}.zip
          tag: ${{ steps.get_version.outputs.tag }}
          overwrite: true
          draft: false
          prerelease: false
