// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/thomas-marquis/s3-box/internal/domain/connection_deck (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package mocks_connection_deck -destination mocks/connection_deck/repository.go github.com/thomas-marquis/s3-box/internal/domain/connection_deck Repository
//

// Package mocks_connection_deck is a generated GoMock package.
package mocks_connection_deck

import (
	context "context"
	io "io"
	reflect "reflect"

	connection_deck "github.com/thomas-marquis/s3-box/internal/domain/connection_deck"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Export mocks base method.
func (m *MockRepository) Export(ctx context.Context, file io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Export indicates an expected call of Export.
func (mr *MockRepositoryMockRecorder) Export(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockRepository)(nil).Export), ctx, file)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context) (*connection_deck.Deck, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(*connection_deck.Deck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx)
}
